export { V2CompositionSchema, type V2Composition } from "./composition";
export {
  V2AssetListSchema,
  V2AssetSchema,
  V2ImageAssetSchema,
  V2FontAssetSchema,
  V2VideoAssetSchema,
  V2VideoAudioDerivativeSchema,
  V2AudioAssetSchema,
  type V2Asset,
  type V2ImageAsset,
  type V2FontAsset,
  type V2VideoAsset,
  type V2VideoAudioDerivative,
  type V2AudioAsset,
} from "./assets";
export {
  V2AudioClipSchema,
  V2AudioDomainSchema,
  V2AudioFadeCurveSchema,
  V2AudioFadeSchema,
  V2EmbeddedVideoAudioSchema,
  V2AudioTrackSchema,
  type V2AudioClip,
  type V2AudioDomain,
  type V2AudioFade,
  type V2EmbeddedVideoAudio,
  type V2AudioFadeCurve,
  type V2AudioTrack,
} from "./audio";
export { V2_AUDIO_FIXTURES, type V2AudioFixture } from "./audio-fixtures";
export {
  V2ColorSchema,
  V2FiniteNumberSchema,
  V2NonNegativeSvgLengthSchema,
  V2MillisecondsSchema,
  V2IdSchema,
  V2NonNegativeNumberSchema,
  V2PositiveNumberSchema,
  V2PositiveSvgLengthSchema,
  V2PositiveMillisecondsSchema,
  V2PaintOrderSchema,
  V2PaintOrderItemSchema,
  V2VectorEffectSchema,
  V2SvgLengthSchema,
  V2SvgLengthUnitSchema,
  type V2PaintOrder,
  type V2PaintOrderItem,
  type V2VectorEffect,
  type V2SvgLength,
  type V2SvgLengthUnit,
} from "./common";
export { MotionProtocolV2Schema } from "./project";
export type { MotionProtocolV2 } from "./types";
export {
  V2OffsetPathSchema,
  V2OffsetRotateSchema,
  V2OffsetAnchorSchema,
  V2MotionPathSchema,
  type V2OffsetPath,
  type V2OffsetRotate,
  type V2OffsetAnchor,
  type V2MotionPath,
} from "./motion-path";
export {
  V2MarkerUnitsSchema,
  V2MarkerOrientSchema,
  V2MarkerViewBoxSchema,
  V2MarkerSchema,
  V2MarkerListSchema,
  V2MarkerReferenceSchema,
  type V2MarkerUnits,
  type V2MarkerOrient,
  type V2MarkerViewBox,
  type V2Marker,
  type V2MarkerList,
} from "./markers";
export {
  V2ClipPathUnitsSchema,
  V2SvgDefinitionTransformSchema,
  V2SvgDefinitionNodeSchema,
  V2ClipPathNodeSchema,
  V2ClipPathSchema,
  V2ClipPathListSchema,
  type V2ClipPathUnits,
  type V2SvgDefinitionNode,
  type V2ClipPath,
  type V2ClipPathList,
} from "./clip";
export {
  V2MaskUnitsSchema,
  V2MaskContentUnitsSchema,
  V2MaskTypeSchema,
  V2MaskCompositeSchema,
  V2MaskLengthSchema,
  V2MaskImageSourceSchema,
  V2MaskSchema,
  V2MaskLayerSchema,
  V2MaskLayerListSchema,
  V2MaskListSchema,
  type V2MaskUnits,
  type V2MaskContentUnits,
  type V2MaskType,
  type V2MaskComposite,
  type V2MaskImageSource,
  type V2MaskLength,
  type V2Mask,
  type V2MaskLayer,
  type V2MaskLayerList,
  type V2MaskList,
} from "./mask";
export {
  V2FilterLengthSchema,
  V2FilterUnitsSchema,
  V2FilterColorInterpolationSchema,
  V2FilterInputSchema,
  V2FilterPrimitiveSchema,
  V2FilterSchema,
  V2FilterListSchema,
  type V2FilterLength,
  type V2FilterInput,
  type V2FilterPrimitive,
  type V2Filter,
  type V2FilterList,
} from "./filter";
export {
  V2PaintTransformSchema,
  V2GradientStopSchema,
  V2GradientFillSchema,
  V2PatternContentSchema,
  V2PatternFillSchema,
  V2PatternViewBoxSchema,
  V2PaintServerSchema,
  V2PaintReferenceSchema,
  V2PaintKeywordSchema,
  V2PaintServerDefinitionSchema,
  V2PaintServerListSchema,
  V2PaintSchema,
  type V2PaintTransform,
  type V2GradientStop,
  type V2GradientFill,
  type V2PatternContent,
  type V2PatternFill,
  type V2PatternViewBox,
  type V2PaintServer,
  type V2PaintReference,
  type V2PaintKeyword,
  type V2PaintServerDefinition,
  type V2Paint,
} from "./paint";
export {
  V2PathPointSchema,
  V2PathSegmentSchema,
  type V2PathPoint,
  type V2PathSegment,
  type V2PathContour,
} from "./path-geometry";
export {
  V2FrameSchema,
  V2LayerBaseSchema,
  V2BlendModeSchema,
  V2IsolationModeSchema,
  V2VisibilitySchema,
  V2CompositeSchema,
  V2GroupLayerSchema,
  V2ImageAlignSchema,
  V2ImagePreserveAspectRatioSchema,
  V2ImageRenderingSchema,
  V2ImageLayerSchema,
  V2VideoFitSchema,
  V2VideoFramePolicySchema,
  V2VideoLayerSchema,
  V2LayerSchema,
  V2PathContourSchema,
  V2PathLayerSchema,
  V2ShapeLayerSchema,
  V2TextFontSchema,
  V2TextDecorationStyleSchema,
  V2TextLayoutSchema,
  V2TextSpanSchema,
  V2TextPathSchema,
  V2TextChunkSchema,
  V2TextSourceSchema,
  V2TextRangeSelectorSchema,
  V2TextLayerSchema,
  type V2Frame,
  type V2BlendMode,
  type V2IsolationMode,
  type V2Composite,
  type V2Visibility,
  type V2GroupLayer,
  type V2ImageAlign,
  type V2ImagePreserveAspectRatio,
  type V2ImageRendering,
  type V2ImageLayer,
  type V2VideoFit,
  type V2VideoFramePolicy,
  type V2VideoLayer,
  type V2Layer,
  type V2PathLayer,
  type V2ShapeLayer,
  type V2TextRange,
  type V2TextFont,
  type V2TextDecorationStyle,
  type V2TextLayout,
  type V2TextSpan,
  type V2TextPath,
  type V2TextChunk,
  type V2TextSource,
  type V2TextRangeSelector,
  type V2TextLayer,
} from "./layers";
export { V2TimingSchema, type V2Timing } from "./timing";
export {
  V2SvgMatrixSchema,
  V2SvgTransformOperationSchema,
  V2TransformSchema,
  V2Vec2Schema,
  V2Vec3Schema,
  type V2SvgMatrix,
  type V2SvgTransformOperation,
  type V2Transform,
  type V2Vec2,
  type V2Vec3,
} from "./transform";
export {
  V2AnimatableValueSchema,
  V2AnimationPlaybackSchema,
  V2TrackPlaybackSchema,
  V2EasingSchema,
  V2InterpolationSchema,
  V2KeyframeSchema,
  V2PropertyPathSchema,
  V2TrackSchema,
  V2TrackListSchema,
  V2KeyframeAnchorSchema,
  V2AnchoredKeyframeTimeSchema,
  V2KeyframeTimeSchema,
  V2LayerKeyframeSchema,
  V2LayerTrackSchema,
  V2LayerTrackListSchema,
  resolveV2KeyframeTime,
  type V2AnimatableValue,
  type V2AnimationPlayback,
  type V2TrackPlayback,
  type V2Easing,
  type V2Interpolation,
  type V2Keyframe,
  type V2PropertyPath,
  type V2Track,
  type V2TrackList,
  type V2KeyframeAnchor,
  type V2AnchoredKeyframeTime,
  type V2KeyframeTime,
  type V2LayerKeyframe,
  type V2LayerTrack,
  type V2LayerTrackList,
} from "./animation";
export {
  V2ProjectionSchema,
  V2ViewSchema,
  type V2Projection,
  type V2View,
} from "./view";
export {
  V2BackfaceVisibilitySchema,
  V2PerspectiveContextSchema,
  V2Render3DSchema,
  V2TransformStyleSchema,
  type V2BackfaceVisibility,
  type V2PerspectiveContext,
  type V2Render3D,
  type V2TransformStyle,
} from "./render3d";
